arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - base_shoulder_joint
    - shoulder_arm_joint
    - arm_elbow_joint
    - elbow_forearm_joint
    - wrist
  gains:
    base_shoulder_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder_arm_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow_forearm_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist:
      p: 100
      d: 1
      i: 1
      i_clamp: 1