controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - base_shoulder_joint
      - shoulder_arm_joint
      - arm_elbow_joint
      - elbow_forearm_joint